apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/hussain.sheriff/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sun, 26 Mar 2023 19:53:04 IST
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: cluster_info
    server: https://127.0.0.1:59685
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sun, 26 Mar 2023 19:53:04 IST
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/hussain.sheriff/.minikube/profiles/minikube/client.crt
    client-key: /Users/hussain.sheriff/.minikube/profiles/minikube/client.key
